/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffba38",
        "surface-bright": "#f8f9fb",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        outline: "#757684",
        "on-primary-fixed": "#000c62",
        "surface-dim": "#d8dadc",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        background: "#f8f9fb",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#8df5e4",
        "on-primary-fixed-variant": "#303c9a",
        "secondary-container": "#8df5e4",
        secondary: "#006b5f",
        "on-primary-container": "#cbcfff",
        "on-tertiary-fixed-variant": "#604100",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007165",
        surface: "#f8f9fb",
        "primary-fixed-dim": "#bcc2ff",
        "on-surface-variant": "#454652",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed": "#ffdeac",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#00201c",
        "secondary-fixed-dim": "#70d8c8",
        "primary-container": "#4551af",
        "on-secondary-fixed-variant": "#005048",
        "on-tertiary-container": "#ffc971",
        "surface-tint": "#4955b3",
        "inverse-on-surface": "#eff1f3",
        tertiary: "#5b3d00",
        "inverse-primary": "#bcc2ff",
        "tertiary-container": "#795300",
        "on-tertiary-fixed": "#281900",
        "inverse-surface": "#2d3133",
        "outline-variant": "#c5c5d4",
        primary: "#2b3896",
        "surface-container": "#eceef0",
        "primary-fixed": "#dfe0ff",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
      },

      fontFamily: {
        headline: ["PlusJakartaSans"],
        body: ["Inter"],
        label: ["Inter"],
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
